# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-03 19:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='adress',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='adress',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='menu_name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
